name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.13.7"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installs Pylint and project dependencies
        pip install pylint
        pip install -r requirements.txt
    - name: Install SpaCy model
      run: |
        # Downloads the SpaCy language model, as in the Dockerfile
        python -m spacy download en_core_web_lg
    - name: Analysing the code with pylint
      run: |
        # Creates a Pylint configuration file to ignore certain style and organization errors.
        echo "[MASTER]" > .pylintrc
        echo "disable=C0301,C0114,R0915,C0411,C0412" >> .pylintrc
        # Runs Pylint on all Python files using the new configuration file.
        pylint $(git ls-files '*.py')
